#!/usr/bin/env python3
"""Generate SOS bandpass coeffs for ESPHome sound_level_meter @ 48 kHz.

Writes:
  - spectrum_filters.json  (1/3-oktáva + oktávy + jemné 5 Hz pásma 190–270)
  - spectrum_fine_esphome.fragment.yaml  (filtry + senzory + ingest řádky)
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from scipy.signal import butter

FS = 48000
BANDS = [
    ("25", 25.0, "third"),
    ("31", 31.5, "third"),
    ("40", 40.0, "third"),
    ("50", 50.0, "third"),
    ("63", 63.0, "third"),
    ("80", 80.0, "third"),
    ("100", 100.0, "third"),
    ("125", 125.0, "third"),
    ("160", 160.0, "third"),
    ("200", 200.0, "third"),
    ("250", 250.0, "third"),
    ("500", 500.0, "octave"),
    ("1k", 1000.0, "octave"),
    ("2k", 2000.0, "octave"),
    ("4k", 4000.0, "octave"),
    ("8k", 8000.0, "octave"),
    ("16k", 16000.0, "octave"),
]

# Lineární 5 Hz středy 190–270 Hz (sousední pásma fc ± 2.5 Hz).
FINE_HZ = tuple(range(190, 271, 5))
FINE_BANDWIDTH = 5.0
FINE_ORDER = 4


def edges(fc: float, kind: str) -> tuple[float, float]:
    r = 2 ** (1 / 6) if kind == "third" else 2**0.5
    return fc / r, fc * r


def fine_edges(fc: float, bw: float = FINE_BANDWIDTH) -> tuple[float, float]:
    half = bw / 2.0
    return fc - half, fc + half


def fmt_sos(sos: np.ndarray) -> list[list[float]]:
    rows = []
    for sec in sos.astype(np.float64):
        b0, b1, b2, a0, a1, a2 = [float(x) for x in sec]
        if abs(a0 - 1.0) > 1e-9:
            b0, b1, b2, a1, a2 = b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0
        b0, b1, b2, a1, a2 = [float(np.float32(x)) for x in (b0, b1, b2, a1, a2)]
        rows.append([b0, b1, b2, a1, a2])
    return rows


def fmt_coeff_yaml(sos: list[list[float]], indent: str = "        ") -> str:
    lines = []
    for row in sos:
        nums = ", ".join(repr(x) for x in row)
        lines.append(f"{indent}- [{nums}]")
    return "\n".join(lines)


def build_fine_fragment(fine_bands: list[dict]) -> str:
    """ESPHome YAML fragment: filters, sensors, ingest spectrum_fine[] lines."""
    filter_blocks: list[str] = []
    sensor_blocks: list[str] = []
    ingest_lines: list[str] = []

    for i, b in enumerate(fine_bands):
        bid = b["id"]  # e.g. "190"
        fid = f"f_fine_{bid}"
        sid = f"fine_{bid}"
        filter_blocks.append(
            f"    # jemné 5 Hz fc={b['fc']} ({b['flo']:.1f}–{b['fhi']:.1f} Hz)\n"
            f"    - id: {fid}\n"
            f"      type: sos\n"
            f"      coeffs:\n"
            f"        # fine fc={b['fc']} bw={FINE_BANDWIDTH} order={FINE_ORDER} @ 48 kHz\n"
            f"{fmt_coeff_yaml(b['sos'])}"
        )
        sensor_blocks.append(
            f"    - type: eq\n"
            f"      name: Fine {bid} Hz\n"
            f"      id: {sid}\n"
            f"      unit_of_measurement: dB\n"
            f"      accuracy_decimals: 1\n"
            f"      update_interval: 1s\n"
            f"      dsp_filters: [f_ics43434, {fid}]"
        )
        ingest_lines.append(f'                root["spectrum_fine"][{i}] = id({sid}).state;')

    header = (
        "# AUTO-GENERATED by scripts/generate_spectrum_filters.py — do not edit by hand.\n"
        f"# Fine 5 Hz bands {FINE_HZ[0]}–{FINE_HZ[-1]} Hz ({len(FINE_HZ)} values).\n"
        "# Paste filters under sound_level_meter.dsp_filters,\n"
        "# sensors under sound_level_meter.sensors,\n"
        "# ingest lines into LAeq 1s http_request.post json block.\n"
    )
    return (
        header
        + "\n# --- filters ---\n"
        + "\n".join(filter_blocks)
        + "\n\n# --- sensors ---\n"
        + "\n".join(sensor_blocks)
        + "\n\n# --- ingest (inside json: |- block; use // comments, not #) ---\n"
        + "                // fine 5 Hz bands 190–270\n"
        + "\n".join(ingest_lines)
        + "\n"
    )


def main() -> None:
    out: dict = {"bands": [], "fine_bands": []}
    out["lfi"] = fmt_sos(butter(4, [20.0, 200.0], btype="band", fs=FS, output="sos"))
    for bid, fc, kind in BANDS:
        flo, fhi = edges(fc, kind)
        fhi = min(fhi, FS / 2 * 0.95)
        flo = max(flo, 5.0)
        order = 4 if kind == "third" else 6
        sos = butter(order, [flo, fhi], btype="band", fs=FS, output="sos")
        out["bands"].append(
            {
                "id": bid,
                "fc": fc,
                "kind": kind,
                "flo": flo,
                "fhi": fhi,
                "order": order,
                "sos": fmt_sos(sos),
            }
        )

    for fc in FINE_HZ:
        flo, fhi = fine_edges(float(fc))
        flo = max(flo, 5.0)
        fhi = min(fhi, FS / 2 * 0.95)
        sos = butter(FINE_ORDER, [flo, fhi], btype="band", fs=FS, output="sos")
        out["fine_bands"].append(
            {
                "id": str(fc),
                "fc": float(fc),
                "kind": "fine5",
                "flo": flo,
                "fhi": fhi,
                "order": FINE_ORDER,
                "bandwidth": FINE_BANDWIDTH,
                "sos": fmt_sos(sos),
            }
        )

    base = Path(__file__).resolve().parent
    path = base / "spectrum_filters.json"
    path.write_text(json.dumps(out, indent=2) + "\n")
    frag = base / "spectrum_fine_esphome.fragment.yaml"
    frag.write_text(build_fine_fragment(out["fine_bands"]))
    print(
        f"wrote {path} ({len(out['bands'])} bands + {len(out['fine_bands'])} fine), "
        f"{frag.name}"
    )


if __name__ == "__main__":
    main()
